# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HyperHMM <- function(obs, initialstates = NULL, seed = 1L, nboot = 100L, fullsample = 1L, outputinput = 0L) {
    .Call(`_hyperhmm_HyperHMM`, obs, initialstates, seed, nboot, fullsample, outputinput)
}

